defaults: &defaults
  action:
    index: '列表'
    new: '新建'
    edit: '编辑'
    show: '详情'
    fixed_wing: '固定翼'
    glider: '滑翔机'
    helicopter: '直升机'
    fpv: '穿越机'
  default_avatar: '/images/avatar.png'

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
