default: &default
  adapter: postgresql
  encoding: utf8
  pool: 50
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: <%= ENV['DB'] %>
  username: <%= ENV['DBUSERNAME'] %>
  password: <%= ENV['DBPASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['DB'] %>
  username: <%= ENV['DBUSERNAME'] %>
  password: <%= ENV['DBPASSWORD'] %>
