default: &default
  adapter: postgresql
  encoding: utf8
  pool: 50
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: rc
  username: postgres
  password: postgres

production:
  <<: *default
  database: rc
  username: postgres
  password: postgres
